name: create_tool_recommendation_model
owner: anuprulez
description: "Create model to recommend tools"
homepage_url: https://github.com/anuprulez/galaxytools
long_description: 
    Create model to recommend tools using deep learning.
remote_repository_url: https://github.com/anuprulez/galaxytools/tree/recommendation_training/tools/tool_recommendation_model
type: unrestricted
categories:
- Workflows
- Deep learning

