name: plotly_regression_performance_plots
owner: bgruening
description: performance plots for regression problems
homepage_url: http://scikit-learn.org/stable/modules/classes.html#module-sklearn.metrics
long_description: |
  The tool creates three plots to measure the performance of a machine learning trained model based on multiple metrics. 
  The metrics include: r2 score, scatter plot of true vs predicted values.
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/plotly_regression_performance_plots
type: unrestricted
categories:
  - Visualization
