name: Cellprofiler
owner: bgruening
categories:
  - Image Analysis
description: Cellprofiler wrapper
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools
type: unrestricted
auto_tool_repositories:
  name_template: "{{ tool_id }}"
  description_template: "Wrapper for Cellprofiler moudule {{ tool_name }}."
suite:
  name: "Cellprofiler"
  description: "A suite of tools that brings the Cellprofiler project into Galaxy."
  long_description: |
      CellProfiler is free, open-source software for quantitative analysis of biological images