categories:
- Computational chemistry
description: Software for protein-compound docking - the prepare ligands step
long_description: |
    Splits a multi-molecucles file, such as a SD file, into single MOL2 format files that can be
    individually docked.
name: autodock_vina_prepare_ligands
owner: tdudgeon
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/chemicaltoolbox/autodock_vina
type: unrestricted
