categories:
  - RNA
description: Align GraphClust predicted cluster sequences and perform consensus structure prediction and conservation evalution.
long_description: |
  Align GraphClust predicted cluster sequences and perform consensus structure prediction and conservation evalution.
name: graphclust_align_cluster
owner: rnateam
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/GraphClust/AlignCluster
